spring.datasource.url=jdbc:postgresql://dpg-d778upchg0os73e6u4i0-a:5432/disaster_db_tbkx
spring.datasource.username=disaster_db_tbkx_user
spring.datasource.password=cZHH3YCA8mrX5pqDDz3nNMPNKp1uzCB0

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080